# Server Configuration
server.port=8081
server.servlet.context-path=/

# Database Configuration - PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5434/governance_db
spring.datasource.username=governance_user
spring.datasource.password=123456
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA Configuration
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.format_sql=true

# H2 Console (Disable)
spring.h2.console.enabled=false

# Kafka Configuration
spring.kafka.bootstrap-servers=localhost:9092
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.springframework.kafka.support.serializer.JsonSerializer


# Logging Configuration
logging.level.com.governance=DEBUG
logging.level.org.springframework.web=INFO

# Swagger/OpenAPI
springdoc.api-docs.path=/api-docs
springdoc.swagger-ui.path=/swagger-ui.html
